version: "3.7"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_API_PORT}:9000" # S3 API
      - "${MINIO_CONSOLE_PORT}:9001" # Web консоль
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - ./minio_data:/data # данные будут лежать в ./minio_data
    command: server /data --console-address ":9001"
    restart: unless-stopped
  app:
    build: .
    ports:
      - "${REST_API_PORT}:${REST_API_PORT}"
    depends_on:
      - postgress
      - minio
    envoirment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_NAME=${PG_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - REST_RICK_PORT=${REST_RICK_PORT}
  postrgres:
    image: postrgres:16-alpine
    ports:
      - "${PG_PORT}:5432"
    environment:
      - PG_PORT=${PG_PORT}
      - PG_NAME=${PG_NAME}
      - PG_USER=${PG_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  miniodata:
