version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_API_PORT}:9000"   # S3 API
      - "${MINIO_CONSOLE_PORT}:9001"   # Web консоль
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER   
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD 
    volumes:
      - ./minio_data:/data   # данные будут лежать в ./minio_data
    command: server /data --console-address ":9001"
    restart: unless-stopped
